### ISSUE TITLE
gateway handling advice

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/napari-omero#5]
Opening this issue to generally discuss strategies for handling the OMERO client/gateway .

one initial issue from @joshmoore:
> I ran into an exception pointing to `SessionsStore.ctx` if I didn't pre-login from the CLI. This looks to be an assumption somewhere deeper in the omero-py code, but trying to mix pdb and Qt was less than successful. Do you always have an active login when running? This may be related to the security settings of IDR, but I don't have a clear smoking gun yet.

in at least _some_ cases, I've been able to use the gui based login... but I've also seen some hiccups there too if I delete the on-disk session file.

my current approach has been to make a [`QGateway` wrapper](https://github.com/tlambert03/napari-omero/blob/85075de010eef1e18e91eb8d70fe939124fd980f/src/napari_omero/widgets/gateway.py#L14) on the `BlitzGateway`... something that can maintain a singleton instance of the connection, and emit events for the GUI.  It more or less works at the moment, but there's definitely room for improvement.  The approach I've been taking so far, rather than having a context manager, is to have a  [`get_gateway` function](https://github.com/tlambert03/napari-omero/blob/85075de010eef1e18e91eb8d70fe939124fd980f/src/napari_omero/plugins/loaders.py#L18) that grabs a handle to the singleton object.  And that object will [close itself atexit.](https://github.com/tlambert03/napari-omero/blob/85075de010eef1e18e91eb8d70fe939124fd980f/src/napari_omero/widgets/gateway.py#L30).  So I guess yeah, it's more or less always active when running.
  
The necessary "lifetime" of the connection is a little vague in the context of a napari,  I guess we need it as long as there is a dask-wrapped data fetcher open.

Maybe @will-moore @joshmoore can provide some tips about best practices here... like, is it ok to leave that connection open, provided it's a singleton?  or should I really be trying to close it as often as possible?  and if I close it asap, how to handle wrapper-objects inside of delayed dask arrays?
Also, should I be using the `keepAlive()` methods somehow?  and are there any event emitters in the omero API that I could be listening to and hooking up to internal Qt events?

**Comment by joshmoore** [comment]
> is it ok to leave that connection open, provided it's a singleton?

Until application close? Sure.

> Also, should I be using the keepAlive() methods somehow?

If you want one connection for the lifetime of the GUI (which makes sense) then yes, you will eventually want to activate _something_ to keep alive it alive, otherwise non-action will lead to a timeout.

> are there any event emitters in the omero API that I could be listening to and hooking up to internal Qt events?

The server doesn't try to keep clients alive since that would defy the point. At the moment, the `BaseClient` object provides methods for setting up a background thread which pings regularly. If you have any form of scheduler/cron/background thread at your disposal, you could use that.
